- hosts: app
  become: true
  roles:
    - role: jdauphant.nginx
      nginx_events_params:
        - worker_connections 1024
        - use epoll
        - multi_accept on
      nginx_configs:
        proxy:
            - proxy_set_header X-Real-IP  $remote_addr
            - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        upstream:
            - upstream myapp { server 127.0.0.1:9292; }
      nginx_http_params:
        - sendfile on
        - access_log /var/log/nginx/access.log
      nginx_sites:
         api_myapp:
           - listen *:80
           - server_name reddit_app
           - location / { proxy_pass  http://myapp/; include /etc/nginx/proxy_params; }
